name: '🚀 CD (Website) — Publish'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.API_GITHUB }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.repository.fork == false && github.ref == 'refs/heads/main' }}
    name: Deploy
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Getting Latest Assets
        run: |
          set +e
          git fetch origin website || true
          git checkout origin/website -- json/maintainers json/projects || true
          mkdir -p content/assets/json/maintainers || true
          mkdir -p content/assets/json/projects || true
          cp -r json/maintainers/* content/assets/json/maintainers/ || true
          cp -r json/projects/* content/assets/json/projects/ || true
          rm -rf json/maintainers json/projects || true

      - name: Installing Dependencies
        run: npm ci

      - name: Checking Types
        run: npm run typecheck

      - name: Checking Lint
        run: npm run lint

      - name: Building Site
        run: |
          npm run build:projects
          npm run build:maintainers
          npm run build

      - name: Deploy — Server
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./server
          publish_branch: 'server'
          allow_empty_commit: false
          enable_jekyll: true

      - name: Deploy — Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./build
          publish_branch: 'website'
          cname: awesomeyou.io
          allow_empty_commit: false
