name: '🔬 CI — Check Projects'

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.API_GITHUB }}
  JSON_CACHE_VERSION: v1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Build and Cache JSON Assets
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore JSON Assets Cache
        id: json-cache
        uses: actions/cache@v4
        with:
          path: content/assets/json
          key: json-assets-${{ runner.os }}-${{ env.JSON_CACHE_VERSION }}
          restore-keys: |
            json-assets-${{ runner.os }}-

      - name: Installing Dependencies
        run: npm ci

      - name: Building Site
        run: npm run build

      - name: Update JSON Assets Cache
        if: steps.json-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: content/assets/json
          key: json-assets-${{ runner.os }}-${{ env.JSON_CACHE_VERSION }}

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Deploy
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Dependencies Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Installing Dependencies
        run: npm ci

      - name: Checking Types
        run: npm run typecheck

      - name: Checking Lint
        run: npm run lint

      - name: Restore JSON Assets Cache
        uses: actions/cache@v4
        with:
          path: content/assets/json
          key: json-assets-${{ runner.os }}-${{ env.JSON_CACHE_VERSION }}
          restore-keys: |
            json-assets-${{ runner.os }}-

      - name: Building Site
        run: npm run build

      - name: Testing Projects
        run: npm test
