name: '🔬 CI — Check Projects'

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.API_GITHUB }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Test
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Dependencies Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Installing Dependencies
        run: npm ci

      - name: Checking Types
        run: npm run typecheck

      - name: Checking Lint
        run: npm run lint

      - name: Restore Projects Cache
        uses: actions/cache@v4
        with:
          path: content/assets/json/projects
          key: json-assets-projects
          restore-keys: |
            json-assets-projects

      - name: Restore Maintainers Cache
        uses: actions/cache@v4
        with:
          path: content/assets/json/maintainers
          key: json-assets-maintainers
          restore-keys: |
            json-assets-maintainers

      - name: Building Site
        run: npm run build

      - name: Testing Projects
        run: npm test
