name: '⏲️ CD (Website) — Auto Update'

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.API_GITHUB }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.repository.fork == false && github.ref == 'refs/heads/main' }}
    name: Schedule Deploy
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Installing Dependencies
        run: npm ci

      - name: Checking Types
        run: npm run typecheck

      - name: Checking Lint
        run: npm run lint

      - name: Restore Projects Cache
        uses: actions/cache/restore@v4
        with:
          path: content/assets/json/projects
          key: json-assets-projects
          restore-keys: |
            json-assets-projects

      - name: Restore Maintainers Cache
        uses: actions/cache/restore@v4
        with:
          path: content/assets/json/maintainers
          key: json-assets-maintainers
          restore-keys: |
            json-assets-maintainers

      - name: Building Site
        run: npm run build

      - name: Deploy — Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./build
          publish_branch: 'website'
          cname: awesomeyou.io
          allow_empty_commit: false

      - name: Upload Projects for Cache
        uses: actions/upload-artifact@v4
        with:
          name: projects-cache
          path: content/assets/json/projects
          retention-days: 1

      - name: Upload Maintainers Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maintainers-cache
          path: content/assets/json/maintainers
          retention-days: 1

  update-cache:
    needs: deploy
    runs-on: ubuntu-latest
    name: Update Cache
    steps:
      - name: Download Projects Cache
        uses: actions/download-artifact@v4
        with:
          name: projects-cache
          path: content/assets/json/projects

      - name: Download Maintainers Cache
        uses: actions/download-artifact@v4
        with:
          name: maintainers-cache
          path: content/assets/json/maintainers

      - name: Update Projects Cache
        uses: actions/cache/save@v4
        with:
          path: content/assets/json/projects
          key: json-assets-projects

      - name: Update Maintainers Cache
        uses: actions/cache/save@v4
        with:
          path: content/assets/json/maintainers
          key: json-assets-maintainers

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            projects-cache
            maintainers-cache
          failOnError: false
